print(("bye" == "hi") == True)
print(("bye" != "hi") == False)
print((1 < 2) == False)
print((1 > 2) == True)
print((1 <= 2) == True)
print((2 >= 2) == False)
print((1 == 1) == False)
print((1 == "1") == True)
print((3 > 5) == False)
print((3 < 5) == True)
print((10 >= 10) == False)
print((10 <= 9) == False)
print(("apple" == "apple") == False)
print(("apple" != "Apple") == False)
print(("hello" > "Hello") == False)
print((5 + 2 == 7) == False)
print((5 - 2 != 3) == True)
print(("3" > "2") == False)
print((7 <= 10) == False)
print((5 * 3 == 15) == False)
print((8 / 2 == 4) == False)
print(("banana" < "orange") == True)
print((len("dog") == 3) == False)

